### ISSUE TITLE
Errors on adapter startup

### ISSUE THREAD

**Issue by Westiewombat** [tim-hellhake/kafka-bridge#6]
Hi Tim

I see these errors when starting the adapter. I have configured the key and kafta server/broker info.. 
Running docker image of Webthings on Ubuntu 20.04 - 6 or 7 things mainly via MySensors but also direct using Webthing adapter

2021-01-30 23:19:15.514 INFO   : Loading add-on: kafka-bridge
2021-01-30 23:19:19.346 INFO   : kafka-bridge: Opening database: /home/node/.webthings/config/db.sqlite3
2021-01-30 23:19:19.525 INFO   : kafka-bridge: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/schema.json because it has no messageType
2021-01-30 23:19:23.645 INFO   : kafka-bridge: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/messages/definitions.json because it has no messageType
2021-01-30 23:19:31.391 INFO   : kafka-bridge: Loading add-on kafka-bridge from /home/node/.webthings/addons/kafka-bridge
2021-01-30 23:20:00.259 ERROR  : kafka-bridge: TypeError: addonLoader is not a function
2021-01-30 23:20:00.261 ERROR  : kafka-bridge:     at /home/node/mozilla-iot/gateway/src/addon-loader.js:110:9
2021-01-30 23:20:00.273 ERROR  : kafka-bridge:     at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by tim-hellhake** [comment]
The new update should fix it.
Please let me know if it works.

**Comment by Westiewombat** [comment]
Hi

Moved on past the errors 
21-02-04 20:28:58.323 INFO   : kafka-bridge: Opening database: /home/node/.webthings/config/db.sqlite3
2021-02-04 20:28:58.530 INFO   : kafka-bridge: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/schema.json because it has no messageType
2021-02-04 20:29:02.700 INFO   : kafka-bridge: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/messages/definitions.json because it has no messageType
2021-02-04 20:29:10.489 INFO   : kafka-bridge: Loading add-on kafka-bridge from /home/node/.webthings/addons/kafka-bridge
2021-02-04 20:29:40.415 INFO   : kafka-bridge: Connecting to kafka at xxxxx.local:9092
2021-02-04 20:29:40.970 INFO   : kafka-bridge: Connecting to gateway
2021-02-04 20:29:40.975 INFO   : kafka-bridge: Probing port 8080

No topic created as per 
bin/kafka-topics.sh  --list  --bootstrap-server PLAINTEXT://xxxxx.local:9092

Can I turn on a debug?

**Comment by tim-hellhake** [comment]
> No topic created as per

I usually use the auto-create option of the kafka broker.
With the next update, the addon will create the topics if they do not exist.

**Comment by tim-hellhake** [comment]
There is also an option for debug logs in the settings now.

**Comment by tim-hellhake** [comment]
@Westiewombat, I just saw that you answered at the addon PR.
I'll reply here to keep things together.

> get-things yields my sensors in json format

Which URL did you supply to the script?

> is this what you expect?

The bridge connects to the local websocket on port 8080 to get updates from the gateway.
Do you use the official raspi image or something else like the docker image?
What version of the gateway are you using?
Are sure the access token you entered is correct?
You can check it using curl:
```
curl -H "Authorization: Bearer YOUR-SECRET-TOKEN" \
  -H "Accept: application/json"  \
  http://localhost:8080/things
```

**Comment by Westiewombat** [comment]
Hi - I'm running the gateway version built into the webthings docker image on Ubuntu 20.04 - version 1.0.0 is announced on the Settings/Upgrade screen ...

I supplied my proxy URL to get-things.sh - the same URL is used for get-devices.sh..

I tried the localhost curl below and received good output back using the pasted JWT token to replace YOUR-SECRET-TOKEN from the token field of the kafka bridge token field - so all good there..
```
curl -H "Authorization: Bearer YOUR-SECRET-TOKEN" \
  -H "Accept: application/json"  \
  http://localhost:8080/things
```

**Comment by tim-hellhake** [comment]
The update uses a new version of the underlying webthings-client.
This should add additional logs for connection errors.
I hope this will give us some insight.

**Comment by Westiewombat** [comment]
0.3.0 updated
All connections happening

```
2021-02-13 07:51:35.411 INFO   : Unloading KafkaBridge
2021-02-13 07:51:46.287 INFO   : Loading add-on: kafka-bridge
2021-02-13 07:51:47.832 INFO   : kafka-bridge: Opening database: /home/node/.webthings/config/db.sqlite3
2021-02-13 07:51:47.906 INFO   : kafka-bridge: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/schema.json because it has no messageType
2021-02-13 07:51:49.780 INFO   : kafka-bridge: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/messages/definitions.json because it has no messageType
2021-02-13 07:51:53.309 INFO   : kafka-bridge: Loading add-on kafka-bridge from /home/node/.webthings/addons/kafka-bridge
2021-02-13 07:52:10.214 INFO   : kafka-bridge: Connecting to kafka at xxxxx.local:9092
2021-02-13 07:52:10.606 INFO   : kafka-bridge: Successfully connected to kafka
2021-02-13 07:52:10.618 INFO   : kafka-bridge: Connecting to gateway
2021-02-13 07:52:10.621 INFO   : kafka-bridge: Probing port 8080
2021-02-13 07:52:10.726 INFO   : kafka-bridge: Successfully connected to the gateway
```
No activity happening with incoming telemetry (should be a Power Pulse Meter Watts, BME sensor Press, Temp, Hum, DHT111 Temp Hum...No new topics being created kafka.

This issue seems to be in this bit of code not detecting the incoming metrics
`
      webThingsClient.on('propertyChanged', async (
        deviceId: string, key: string, value: unknown) => {
        const topic = deviceId.replace(/[^a-zA-Z0-9\\._-]/g, '_');
`
I selected only the devices that produce telemetry and didn't select ones that have actuators when creating the key. I'll test with selecting only 1, then also will all devices and come back.

**Comment by tim-hellhake** [comment]
> I selected only the devices that produce telemetry and didn't select ones that have actuators when creating the key. I'll test with selecting only 1, then also will all devices and come back.

That would explain the issue.
The gateway is only sending events for the devices you selected.

**Comment by Westiewombat** [comment]
Much better :) - detecting changes - now having issues creating topics with kafka server :(

2021-02-15 17:30:15.727 INFO   : Unloading KafkaBridge
2021-02-15 17:30:27.667 INFO   : Loading add-on: kafka-bridge
2021-02-15 17:30:38.233 INFO   : kafka-bridge: Opening database: /home/node/.webthings/config/db.sqlite3
2021-02-15 17:30:38.647 INFO   : kafka-bridge: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/
schema.json because it has no messageType
2021-02-15 17:30:40.927 INFO   : kafka-bridge: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/
messages/definitions.json because it has no messageType
2021-02-15 17:30:44.520 INFO   : kafka-bridge: Loading add-on kafka-bridge from /home/node/.webthings/addons/kafka-bridge
2021-02-15 17:31:18.884 INFO   : kafka-bridge: Connecting to kafka at xxxx.local:9092
2021-02-15 17:31:19.263 INFO   : kafka-bridge: Successfully connected to kafka
2021-02-15 17:31:19.267 INFO   : kafka-bridge: Connecting to gateway
2021-02-15 17:31:19.271 INFO   : kafka-bridge: Probing port 8080
2021-02-15 17:31:19.379 INFO   : kafka-bridge: Successfully connected to the gateway
2021-02-15 17:31:19.414 INFO   : kafka-bridge: Topic http---weathersensor.local-things-bme280 does not exist, attempting to create it
2021-02-15 17:31:19.430 INFO   : kafka-bridge: Topic create for http---weathersensor.local-things-bme280 is in progress, queueing message
2021-02-15 17:31:19.438 INFO   : kafka-bridge: Topic create for http---weathersensor.local-things-bme280 is in progress, queueing message
2021-02-15 17:31:19.443 INFO   : kafka-bridge: Topic MySensors-78 does not exist, attempting to create it
2021-02-15 17:31:19.451 INFO   : kafka-bridge: Topic create for MySensors-78 is in progress, queueing message
2021-02-15 17:31:19.459 INFO   : kafka-bridge: Topic MySensors-3 does not exist, attempting to create it
2021-02-15 17:31:19.467 INFO   : kafka-bridge: Topic MySensors-2 does not exist, attempting to create it
2021-02-15 17:31:19.475 INFO   : kafka-bridge: Topic create for MySensors-2 is in progress, queueing message
2021-02-15 17:31:19.486 INFO   : kafka-bridge: Topic create for MySensors-2 is in progress, queueing message
2021-02-15 17:31:19.498 INFO   : kafka-bridge: Topic create for MySensors-2 is in progress, queueing message
2021-02-15 17:31:19.524 INFO   : kafka-bridge: Topic MySensors-79 does not exist, attempting to create it
2021-02-15 17:31:19.530 INFO   : kafka-bridge: Topic create for MySensors-79 is in progress, queueing message
2021-02-15 17:31:19.540 INFO   : kafka-bridge: Topic MySensors-81 does not exist, attempting to create it
2021-02-15 17:31:19.544 INFO   : kafka-bridge: Topic create for MySensors-81 is in progress, queueing message
2021-02-15 17:31:24.373 INFO   : kafka-bridge: Topic create for MySensors-2 is in progress, queueing message
2021-02-15 17:31:34.427 INFO   : kafka-bridge: Topic create for MySensors-2 is in progress, queueing message
2021-02-15 17:31:35.315 INFO   : kafka-bridge: Topic create for MySensors-81 is in progress, queueing message
2021-02-15 17:31:49.425 INFO   : kafka-bridge: Could not create topic http---weathersensor.local-things-bme280: TimeoutError: Request timed out after 30000ms
2021-02-15 17:31:49.443 INFO   : kafka-bridge: Could not create topic MySensors-78: TimeoutError: Request timed out after 30000ms
2021-02-15 17:31:49.461 INFO   : kafka-bridge: Could not create topic MySensors-3: TimeoutError: Request timed out after 30000ms
2021-02-15 17:31:49.468 INFO   : kafka-bridge: Could not create topic MySensors-2: TimeoutError: Request timed out after 30000ms
2021-02-15 17:31:49.525 INFO   : kafka-bridge: Could not create topic MySensors-79: TimeoutError: Request timed out after 30000ms
2021-02-15 17:31:49.541 INFO   : kafka-bridge: Could not create topic MySensors-81: TimeoutError: Request timed out after 30000ms
2021-02-15 17:31:54.522 INFO   : kafka-bridge: Topic create for MySensors-2 is in progress, queueing message
2021-02-15 17:32:01.635 INFO   : kafka-bridge: Topic create for MySensors-78 is in progress, queueing message
2021-02-15 17:32:14.629 INFO   : kafka-bridge: Topic create for MySensors-2 is in progress, queueing message
2021-02-15 17:32:15.327 INFO   : kafka-bridge: Topic create for MySensors-81 is in progress, queueing message
`

**Comment by Westiewombat** [comment]
Update - looking good:
Adding auto.create.topics.enable=true to the server.properties allowed the messages to come through 
2021-02-15 21:27:57.200 INFO   : kafka-bridge: Sending {
2021-02-15 21:27:57.202 INFO   : kafka-bridge:   "topic": "MySensors-78",
2021-02-15 21:27:57.204 INFO   : kafka-bridge:   "key": "78-1-0",
2021-02-15 21:27:57.205 INFO   : kafka-bridge:   "messages": 27.9
2021-02-15 21:27:57.207 INFO   : kafka-bridge: }

~kafka/kafka/bin/kafka-console-consumer.sh --topic MySensors-78 --property print.key=true --from-beginning  --bootstrap-server localhost:9092
78-1-0  27.8
78-0-1  52.5
78-1-0  27.9
78-0-1  52.6

**Comment by tim-hellhake** [comment]
I think I found out why your token didn't work.
If the token has no permission to read all devices you cant's use the `things` websocket.
You need to connect to the individual device websockets instead.
The next update will allow you to use tokens with a limited scope.

**Comment by Westiewombat** [comment]
I'm trying to build a kafka sink for the readings - initially to MongoDB
I see that the kafka data type for key written is string, how about the values are they string data type too, or do they follow the Webthings schema - eg key string, number for Energy Monitor watts  or Temperature/Pressure?

2021-03-03 10:05:27.833 INFO   : kafka-bridge: Sending {
2021-03-03 10:05:27.835 INFO   : kafka-bridge:   "topic": "MySensors-81",
2021-03-03 10:05:27.837 INFO   : kafka-bridge:   "key": "81-1-18",
2021-03-03 10:05:27.839 INFO   : kafka-bridge:   "messages": 832.29
2021-03-03 10:05:27.843 INFO   : kafka-bridge: }

**Comment by Westiewombat** [comment]
Just wondering if it were possible to write the value as JSON using the webthings schema?

**Comment by tim-hellhake** [comment]
You mean the complete property description instead of just the value?

**Comment by Westiewombat** [comment]
Just a thought. Perhaps a setting toggle. I can't speak from experience but using the MongoDB adapter seems to require this .. could be the only one https://docs.mongodb.com/kafka-connector/current/kafka-sink-properties/

I have a discussion on the MongoDB forum, discussing the issue ...https://developer.mongodb.com/community/forums/t/error-unable-to-process-record-sinkrecord/16857/2

**Comment by tim-hellhake** [comment]
> I have a discussion on the MongoDB forum, discussing the issue ...https://developer.mongodb.com/community/forums/t/error-unable-to-process-record-sinkrecord/16857/2

I see that helps a lot in understanding the problem.
The next update will add an option to send values as JSON.
The payload of the message will look like this: `{"temperature":20}`.
You need to use the `JsonConverter` for the values.

**Comment by tim-hellhake** [comment]
You will still need to think about how you want to organize your database.

MongoDB has a `database`, a `collection`, and the document itself.
The `kafka-bridge` publishes the data as follows:

`topic`: device id
`message key`: property name
`message value`: `{[property name]: [property value]}`.

Normally you configure a `topic` and a corresponding `database` and `collection` in the sink.
If you only want to save a few devices this might be feasible.
If you want to organize your devices into multiple `collections` automatically you might wanna take a look a the `namespace.mapper` config parameter.
If you use the [FieldPathNamespaceMapper](https://docs.mongodb.com/kafka-connector/current/kafka-sink-properties/#std-label-fieldpathnamespacemapper-settings) you can instruct the sink to use a specific field in the key or value document as a collection of the database name.
Which makes me think about the Kafka key.
I think this needs to be also a JSON document for it to work.

**Comment by tim-hellhake** [comment]
You will still need to think about how you want to organize your database.

MongoDB has a `database`, a `collection`, and the document itself.
The `kafka-bridge` publishes the data as follows:

`topic`: device id
`message key`: property name
`message value`: `{[property name]: [property value]}`.

Normally you configure a `topic` and a corresponding `database` and `collection` in the sink.
If you only want to save a few devices, this might be feasible.
If you want to organize your devices into multiple `collections` automatically, you might wanna take a look a the `namespace.mapper` config parameter.
If you use the [FieldPathNamespaceMapper](https://docs.mongodb.com/kafka-connector/current/kafka-sink-properties/#std-label-fieldpathnamespacemapper-settings), you can instruct the sink to use a specific field in the key or value document as a collection of the database name.
Which makes me think about the Kafka key.
I think this needs to be also a JSON document for it to work.

**Comment by tim-hellhake** [comment]
You will still need to think about how you want to organize your database.

MongoDB has a database, a collection, and the document itself.
The kafka-bridge publishes the data as follows:

topic: device id
message key: property name
message value: {[property name]: [property value]}.

Normally you configure a topic and a corresponding database and collection in the sink.
If you only want to save a few devices, this might be feasible.
If you want to organize your devices into multiple collections automatically, you might wanna take a look a the namespace.mapper config parameter.
If you use the FieldPathNamespaceMapper, you can instruct the sink to use a specific field in the key or value document as a collection or database name.
Which makes me think about the Kafka key.
I think this needs to be also a JSON document for it to work.

**Comment by Westiewombat** [comment]
Hi - this is the output with JSON selected. I allows the connector to work to MongoDB .. but the database is difficult to read without coding to interpret the data - so simple visualisation is tricky 
{"81-0-17":868}
{"81-1-18":1057.01}
{"81-0-17":923}
{"81-1-18":1057.02}
{"81-0-17":907}
{"81-1-18":1057.03}

It would be useful to have the data in more readable form - exploded from webthings schema
{ “name”:“81-0-17,” "reading":"watts",“value”:1304}
{ “name”:“81-1-18”, "reading":"kwh" “value”: 1057.02}

I could write an SMT to code it into the sink, but why not add it to the kafka topic?

**Comment by tim-hellhake** [comment]
The setting changed a bit with the new update.
You can now select between `string`, `json` and `json+description`.
If you select `json` you get something like `{"name": "power", "value": 42}`.
If you select `json+description` you get the `json` plus the fields of the property description such as `unit` and `type`.

**Comment by Westiewombat** [comment]
I have tried out json and json+description with all my sensors - looking good. I'll stick to json+description, so I have the opportunity to extract what I need.Thankyou
